Repository Jinmiru/opensource-sw-final-project, pull requests merged in 2024-12, with the labels that each got.

#13 Update README.md
  README.md
Labels: documentation

#20 2048 게임 병합
  hello.py
  pages/Game2048.py
Labels: develop

#22 Feature/readme
  README.md
Labels: documentation

#26 스도쿠 게임 재커밋
  Game2048.py
  GameSudoku.py
Labels: enhancement

#29 Update README.md
  README.md
Labels: documentation, develop

#36 Tutorial 페이지 추가
  README.md
  hello.py
  tutorial.py
Labels: documentation, develop

#44 Game2048 수정
  pages/Game2048.py
Labels: bug, develop

#47 Feature/2048
  README.md
  pages/Game2048.py
Labels: enhancement, develop

#51 점수 기능 위치 수정 및 uchat 제거
  pages/Game2048.py
Labels: develop, feature

#54 회의록 및 패치노트
  회의록 및 패치노트/2024.11.27(수)_오픈소스SW의이해8조_회의록(수정).pdf
  회의록 및 패치노트/2024.11.30(수)_오픈소스SW의이해8조_회의록.pdf
  회의록 및 패치노트/2024.12.04(수) 8조_회의록.pdf
  회의록 및 패치노트/8조_날짜별 진행사항_패치노트.txt
Labels: documentation, feature

#56 Feature/readme
  README.md
Labels: documentation, enhancement

#55 js_test.py 내용 수정
  module/js_test.py
  pages/Game2048.py
  pages/uchat.py
Labels: bug, develop

#59 GameSudoku.py Uchat 기능 삭제
  pages/GameSudoku.py
Labels: bug, develop

#64 날씨 위젯 추가 및 유챗 페이지 제거
  images/game7.png
  images/game8.png
  images/game9.png
  images/icon.png
  images/logo.png
  images/title.png
  main.py
  module/clock.py
  module/weather.py
  pages/Game2048.py
  pages/GameSnake.py
  pages/GameSudoku.py
  pages/chromedino.py
  pages/flappybird.py
  pages/pacman.py
  pages/puzzleBobble.py
  pages/solitare.py
  pages/tetris.py
  pages/tutorial.py
Labels: enhancement, develop

#65 main으로 develop 브랜치 병합
  .gitignore
  LICENSE
  README.md
  images/game1.png
  images/game2.png
  images/game3.png
  images/game4.png
  images/game5.png
  images/game6.png
  images/game7.png
  images/game8.png
  images/game9.png
  images/icon.png
  images/logo.png
  images/title.png
  main.py
  module/clock.py
  module/js_test.py
  module/weather.py
  pages/Game2048.py
  pages/GameSnake.py
  pages/GameSudoku.py
  pages/chromedino.py
  pages/flappybird.py
  pages/pacman.py
  pages/puzzleBobble.py
  pages/solitare.py
  pages/tetris.py
  pages/tutorial.py
  requirements.txt
Labels: documentation, enhancement, main

#68 이미지 경로를 다 깃허브 URL로 바꿨습니다
  .devcontainer/devcontainer.json
  main.py
  pages/Game2048.py
  pages/GameSnake.py
  pages/chromedino.py
  pages/flappybird.py
  pages/pacman.py
  pages/puzzleBobble.py
  pages/solitare.py
  pages/tetris.py
Labels: bug

#69 README 사용 방법 수정
  README.md
Labels: documentation, develop

#70 Develop 브랜치를 main으로 병합
  .devcontainer/devcontainer.json
  README.md
  main.py
  pages/Game2048.py
  pages/GameSnake.py
  pages/chromedino.py
  pages/flappybird.py
  pages/pacman.py
  pages/puzzleBobble.py
  pages/solitare.py
  pages/tetris.py
Labels: bug, documentation, main
